// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
)

type GameStat struct {
	ID        int64
	CreatedAt sql.NullTime
}

type User struct {
	ID           int64
	Name         string
	PasswordHash string
	CreatedAt    sql.NullTime
}
