// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
)

type User struct {
	ID           int64
	Name         string
	PasswordHash string
	CreatedAt    sql.NullTime
}
