// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package db

import (
	"context"
)

const createGameStat = `-- name: CreateGameStat :one
INSERT INTO game_stats (created_at)
VALUES (CURRENT_TIMESTAMP)
RETURNING id, created_at
`

func (q *Queries) CreateGameStat(ctx context.Context) (GameStat, error) {
	row := q.db.QueryRowContext(ctx, createGameStat)
	var i GameStat
	err := row.Scan(&i.ID, &i.CreatedAt)
	return i, err
}

const getGameStats = `-- name: GetGameStats :many
SELECT id, created_at FROM game_stats
ORDER BY created_at DESC
`

func (q *Queries) GetGameStats(ctx context.Context) ([]GameStat, error) {
	rows, err := q.db.QueryContext(ctx, getGameStats)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GameStat
	for rows.Next() {
		var i GameStat
		if err := rows.Scan(&i.ID, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
